### ISSUE TITLE
Checking for header util/data_blob.h     : not found

### ISSUE THREAD

**Issue by dagnum** [bitlair/siahsd#1]
Hello!  I am very excited to get to test this software but after a week of trying to install it to CENTOS 6.5 I am unsuccessful.  After about a year of searching I have found a TCP/IP based Security System.  It is not too shabby but of course limited in what it can do.  That is why I am so excited to find your SIA server software.  The TCP/IP Alarm System has a simple configuration to connect to SIA server.

I am working through the dependencies but cannot get past this one:

"Checking for header util/data_blob.h     : not found"

I can clearly see it comes with Samba and I can see that i do have the header but it insists it is not found.  I have been told by a linux dev hired to look into it that it is due to samba coding issues and he spent hours on it without making much progress.

Can you recommend any other OS or other ideal configuration you recommend?

[root@sia-server-01 siahsd-master]# uname -a
Linux sia-server-01 2.6.32-504.23.4.el6.x86_64 #1 SMP Tue Jun 9 20:57:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

[root@sia-server-01 siahsd-master]# cat /etc/redhat-release
CentOS release 6.6 (Final)

[root@sia-server-01 siahsd-master]# waf configure
Setting top to                           : /home/siahsd-master 
Setting out to                           : /home/siahsd-master/build 
Checking for program gcc,cc              : gcc 
Checking for program ar                  : /usr/bin/ar 
Checking for program pkg-config          : /usr/bin/pkg-config 
Checking for 'glib-2.0'                  : yes 
Checking for 'talloc'                    : yes 
Checking for 'tevent'                    : yes 
Checking for 'samba-util'                : yes 
Checking for 'ndr'                       : yes 
Checking for header stdio.h              : yes 
Checking for header stdlib.h             : yes 
Checking for header stdint.h             : yes 
Checking for header stdbool.h            : yes 
Checking for header sys/time.h           : yes 
Checking for header sys/types.h          : yes 
Checking for header sys/stat.h           : yes 
Checking for header netinet/in.h         : yes 
Checking for header arpa/inet.h          : yes 
Checking for header unistd.h             : yes 
Checking for header string.h             : yes 
Checking for header fcntl.h              : yes 
Checking for header errno.h              : yes 
Checking for header talloc.h             : yes 
Checking for header glib.h               : yes 
Checking for header glibconfig.h         : yes 
Checking for header dbi/dbi.h            : yes 
Checking for header util/data_blob.h     : not found 

Thank you sir and keep up the great work!

**Comment by newb33** [comment]
same problem here with:
glibconfig.h
util/data_blob.h
core/ntstatus.h
charset.h

**Comment by dagnum** [comment]
FOUND THE PROBLEM!!!!

vi /usr/include/samba-4.0/util/data_blob.h
and add INCLUDE:

`#include <stdbool.h>`

Its some CRAP with BOOL

@Sabre.Tooth Use it like a normal type. So wherever you would write bool you could also write _Bool. The fact is _Bool is the "real" type, introduced in C99 and bool is just an alias. They couldn't introduce bool since it wasn't a reserved keyword in previous standards so it would have broken programs already using it.

SEE HERE: http://stackoverflow.com/questions/15183860/my-linuxs-gcc-compiler-not-supporting-boolean-value

**Comment by dagnum** [comment]
Now moving on to the next issue:
Checking for header core/ntstatus.h      : not found
